version: '3'
services:
   
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        environment:
            - discovery.type=single-node
        volumes:
            - esdata:/usr/share/elasticsearch/data
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9200:9200

    logstash:
        image: docker.elastic.co/logstash/logstash:7.14.0
        volumes:
            - ./pipeline/:/usr/share/logstash/pipeline/
            - /etc/localtime:/etc/localtime:ro
        links:
            - elasticsearch
            - redis
    redis:
        image: redis
        volumes:
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 6379:6379
    
    app:
        build: 
            context: ./app
            args: 
                - LOGSOURCE=/var/log/nginx/access.log
        volumes:
            - /var/log/nginx:/var/log/nginx
            - /var/log/apache2:/var/log/apache2
        links: 
            - redis
        depends_on: 
            - redis

volumes:
    esdata:
        driver: local